//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lots_of_Checklists.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Entries
    {
        public int EntryId { get; set; }
        public string Name { get; set; }
        public bool IsChecked { get; set; }
        public bool IsDeleted { get; set; }
        public int ChecklistID { get; set; }
    
        public virtual Checklists Checklists { get; set; }
    }
}
