//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lots_of_Checklists
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string Description { get; set; }
        public bool IsChecked { get; set; }
        public int ChecklistID { get; set; }
    
        public virtual Checklist Checklist { get; set; }
    }
}
